from .small_function_collection import extract_numbers,ceiling_division
from .small_function_collection import select_backend, obtain_info_2q_basis_gate, obtain_best_trans_qc
from .small_function_collection import execute_circuits_on_simulator,execute_circuits_on_real_machine, retrive_job_from_real_machine
from .small_function_collection import obtain_info_1q_gate_qaoa
from .small_function_collection import obtain_average_num_2q_basis_gate
from .small_function_collection import get_ancestors_circuit
